apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
data:
  GATEWAY_PORT: "8080"
  USERS_PORT: "50051"
  LEARN_PORT: "50052"
  AISRV_PORT: "50053"
  FRONT_PORT: "5173"

  USERS_HOST: "users-service"
  LEARN_HOST: "learn-service"
  AISRV_HOST: "ai-service"

  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres"
  REDIS_PORT: "6379"

  OLLAMA_PORT: "11434"
  AI_HOST: "ollama"
  AI_PORT: "11434"

  REDIS_SM_ADDR: "redis-sm:6379"
  REDIS_LRN_ADDR: "redis-lrn:6379"
  REDIS_RL_ADDR: "redis-rl:6379"
  REDIS_AI_ADDR: "redis-ai:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
type: Opaque
stringData:
  POSTGRES_DB: "enbooster_db"
  POSTGRES_USER: "enbooster"
  POSTGRES_PASSWORD: "1234"
  POSTGRES_URL: "postgres://enbooster:1234@postgres:5432/enbooster_db?sslmode=disable"

  REDIS_SM_PASSWORD: "redis_sm_pass"
  REDIS_LRN_PASSWORD: "redis_lrn_pass"
  REDIS_RL_PASSWORD: "redis_rl_pass"
  REDIS_AI_PASSWORD: "redis_ai_pass"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  POLLER_TIMEOUT: "10"
  REDIS_CTX_TIMEOUT: "10"
  REDIS_PING_TIMEOUT: "10"
  STATE_TTL: "30"
  HISTORY_TTL: "60"
  CTX_TIMEOUT: "10"
  AI_TIMEOUT: "30"
  CB_MAX_REQUESTS: "5"
  CB_TIMEOUT: "20"
  CB_INTERVAL: "30"
  CB_FAIL_CNT: "5"
  RATE_LIMIT_TTL: "1800"
  RATE_LIMIT: "100"
  LANG_LEVELS: "A1 A2 B1 B2 C1 C2"
  KAFKA_GROUP_ID: "us-gtw-notify"
  NOTIFICATION_MESSAGES: "Time to practice your English! The owl is watching... 👀; English won't learn itself! Just 5 minutes today.; Hey, you forgot your English lesson today!; Your English streak is crying. Save it now!; 5 minutes of English a day keeps the ignorance away!; Ready for your daily English workout?; Don't let your streak break! Do a quick lesson.; Time to shine! Practice your English now.; A little bit of English every day makes a huge difference.; Where are you? Your English vocabulary misses you!; Quick English break? Let's go!; Keep your momentum going—time for English!; Don't make me come find you... practice your English! 🦉; Make your future self proud! Do your English lesson.; Just one lesson today, and you're good to go!"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
data:
  MAX_OPEN_CONNS: "15"
  MAX_IDLE_CONNS: "10"
  MAX_LIFETIME: "15"
  MAX_IDLETIME: "10"
  CTX_TIMEOUT: "10"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: learn-config
data:
  MAX_OPEN_CONNS: "15"
  MAX_IDLE_CONNS: "10"
  MAX_LIFETIME: "15"
  MAX_IDLETIME: "10"
  REDIS_PING_TIMEOUT: "10"
  REDIS_TIMEOUT: "30"
  COUNT_TTL: "1800"
  TASK_TTL: "30"
  GET_LIMIT: "10"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-config
data:
  REDIS_PING_TIMEOUT: "10"
  REDIS_TIMEOUT: "20"
  REDIS_CTX_TTL: "10"
  AI_MODEL: "qwen2.5:7b"
  AI_TIMEOUT: "60"
  AI_TEMP: "0.7"
  AI_NUM_PREDICTS: "512"
  AI_TOP_P: "0.95"
  AI_REPEAT_PENALTY: "1.1"
  AI_DEFAULT_SYSTEM_PROMPT: "You are Alex, a chill, slightly sarcastic native English speaker. You are text-mating with the user, who is your close friend. Rules: 1. Speak like a real person in a chat. Use casual contractions, slang, and modern idioms. 2. Keep your replies short (max 2-3 sentences). No one likes walls of text. 3. Absolutely never sound like a textbook, a teacher, or a customer service bot. 4. Never apologize or lecture. Just keep the banter going with wit and dark humor."
  TTS_SAMPLE_RATE: "16000"
  TTS_PATH: "./scripts/rhvoice"
  TTS_MODEL: "anna"
  STT_SAMPLE_RATE: "16000"
  STT_PATH: "./scripts/vosk-model-small-en-us-0.15"
