apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-local
  template:
    metadata:
      labels:
        app: postgres-local
    spec:
      containers:
        - name: postgres
          image: postgres:17
          env:
            - name: POSTGRES_USER
              value: "enbooster"
            - name: POSTGRES_DB
              value: "enbooster_db"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: enbooster-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-users
              mountPath: /docker-entrypoint-initdb.d/1-users.sql
              subPath: 1-users.sql
            - name: init-learn
              mountPath: /docker-entrypoint-initdb.d/2-learn.sql
              subPath: 2-learn.sql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-users
          configMap:
            name: postgres-init-users
        - name: init-learn
          configMap:
            name: postgres-init-learn
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-local
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-local
