apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sm
  template:
    metadata:
      labels:
        app: redis-sm
    spec:
      containers:
        - name: redis
          image: redis:alpine
          command: ["redis-server", "--requirepass", "$(REDIS_SM_PASSWORD)", "--loglevel", "warning"]
          env:
            - name: REDIS_SM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: REDIS_SM_PASSWORD
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sm
spec:
  type: ClusterIP
  selector:
    app: redis-sm
  ports:
    - port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-lrn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-lrn
  template:
    metadata:
      labels:
        app: redis-lrn
    spec:
      containers:
        - name: redis
          image: redis:alpine
          command: ["redis-server", "--requirepass", "$(REDIS_LRN_PASSWORD)", "--loglevel", "warning"]
          env:
            - name: REDIS_LRN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: REDIS_LRN_PASSWORD
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-lrn
spec:
  type: ClusterIP
  selector:
    app: redis-lrn
  ports:
    - port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-rl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-rl
  template:
    metadata:
      labels:
        app: redis-rl
    spec:
      containers:
        - name: redis
          image: redis:alpine
          command: ["redis-server", "--requirepass", "$(REDIS_RL_PASSWORD)", "--loglevel", "warning"]
          env:
            - name: REDIS_RL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: REDIS_RL_PASSWORD
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-rl
spec:
  type: ClusterIP
  selector:
    app: redis-rl
  ports:
    - port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-ai
  template:
    metadata:
      labels:
        app: redis-ai
    spec:
      containers:
        - name: redis
          image: redis:alpine
          command: ["redis-server", "--requirepass", "$(REDIS_AI_PASSWORD)", "--loglevel", "warning"]
          env:
            - name: REDIS_AI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: REDIS_AI_PASSWORD
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-ai
spec:
  type: ClusterIP
  selector:
    app: redis-ai
  ports:
    - port: 6379
      targetPort: 6379
