syntax = "proto3";

package ai;
option go_package = "generated-ai/;aiservice";

message GenerateTextReq {
  string prompt = 1;
  string system_prompt = 2;
  string request_trace = 3;
}
message GenerateTextRes {
  string text = 1;
}

message GenerateAudioReq {
  string text = 1;
  string request_trace = 2;
}
message GenerateAudioRes {
  bytes audio_data = 1;
}

message RecognizeAudioReq {
  bytes audio_data = 1;
  string request_trace = 2;
}
message RecognizeAudioRes {
  string text = 1;
}

message ClearAIContextReq {
  int64 uuid = 1;
  string request_trace = 2;
}
message ClearAIContextRes {}

message ChangeModelReq {
  string model = 1;
  string request_trace = 2;
}
message ChangeModelRes {}

service AIService {
  rpc GenerateText (GenerateTextReq) returns (stream GenerateTextRes);
  rpc GenerateAudio (GenerateAudioReq) returns (GenerateAudioRes);
  rpc RecognizeAudio (RecognizeAudioReq) returns (stream RecognizeAudioRes);
  rpc ClearAIContext (ClearAIContextReq) returns (ClearAIContextRes);
  rpc ChangeModel (ChangeModelReq) returns (ChangeModelRes);
}
