syntax = "proto3";

package users;
option go_package="generated-users/;usersservice";

message GetReq {
  string request_trace = 1;
}
message GetRes {
  string data = 1; // json
}

message UpdSystemPromptReq {
  string system_prompt = 1;
  string request_trace = 2;
}
message UpdSystemPromptRes {}

message UpdLangLevelReq {
  string level = 1;
  string request_trace = 2;
}
message UpdLangLevelRes {}

message UpdStreakReq {
  bool correct  = 1;
  string theme = 2;
  int32 counter = 3;
  string request_trace = 4;
}
message UpdStreakRes {}

service UsersService {
  rpc GetUser (GetReq) returns (GetRes);
  rpc UpdSystemPrompt (UpdSystemPromptReq) returns (UpdSystemPromptRes);
  rpc UpdLangLevel (UpdLangLevelReq) returns (UpdLangLevelRes);
  rpc UpdStreak (UpdStreakReq) returns (UpdStreakRes);
}
