syntax = "proto3";

package users;
option go_package="generated-users/;usersservice";

message RegReq {
  string request_trace = 1;
}
message RegRes {}

message GetReq {
  string request_trace = 1;
}
message GetRes {
  string data = 1; // json
}

message UpdSystemPromptReq {
  string system_prompt = 1;
  string request_trace = 2;
}
message UpdSystemPromptRes {}

message UpdLangLevelReq {
  string level = 1;
  string request_trace = 2;
}
message UpdLangLevelRes {}

service UsersService {
  rpc RegUser (RegReq) returns (RegRes);
  rpc GetUser (GetReq) returns (GetRes);
  rpc UpdSystemPrompt (UpdSystemPromptReq) returns (UpdSystemPromptRes);
  rpc UpdLangLevel (UpdLangLevelReq) returns (UpdLangLevelRes);
}
