// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ai.proto

package aiservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateTextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          int64                  `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,4,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTextReq) Reset() {
	*x = GenerateTextReq{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTextReq) ProtoMessage() {}

func (x *GenerateTextReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTextReq.ProtoReflect.Descriptor instead.
func (*GenerateTextReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateTextReq) GetUuid() int64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *GenerateTextReq) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateTextReq) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *GenerateTextReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type GenerateTextRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTextRes) Reset() {
	*x = GenerateTextRes{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTextRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTextRes) ProtoMessage() {}

func (x *GenerateTextRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTextRes.ProtoReflect.Descriptor instead.
func (*GenerateTextRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateTextRes) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GenerateAudioReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          int64                  `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,3,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAudioReq) Reset() {
	*x = GenerateAudioReq{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAudioReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAudioReq) ProtoMessage() {}

func (x *GenerateAudioReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAudioReq.ProtoReflect.Descriptor instead.
func (*GenerateAudioReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateAudioReq) GetUuid() int64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *GenerateAudioReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateAudioReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type GenerateAudioRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAudioRes) Reset() {
	*x = GenerateAudioRes{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAudioRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAudioRes) ProtoMessage() {}

func (x *GenerateAudioRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAudioRes.ProtoReflect.Descriptor instead.
func (*GenerateAudioRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateAudioRes) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

type RecognizeAudioReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          int64                  `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,3,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeAudioReq) Reset() {
	*x = RecognizeAudioReq{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeAudioReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeAudioReq) ProtoMessage() {}

func (x *RecognizeAudioReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeAudioReq.ProtoReflect.Descriptor instead.
func (*RecognizeAudioReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *RecognizeAudioReq) GetUuid() int64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *RecognizeAudioReq) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *RecognizeAudioReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type RecognizeAudioRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeAudioRes) Reset() {
	*x = RecognizeAudioRes{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeAudioRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeAudioRes) ProtoMessage() {}

func (x *RecognizeAudioRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeAudioRes.ProtoReflect.Descriptor instead.
func (*RecognizeAudioRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *RecognizeAudioRes) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ClearAIContextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          int64                  `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,2,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAIContextReq) Reset() {
	*x = ClearAIContextReq{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAIContextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAIContextReq) ProtoMessage() {}

func (x *ClearAIContextReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAIContextReq.ProtoReflect.Descriptor instead.
func (*ClearAIContextReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ClearAIContextReq) GetUuid() int64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *ClearAIContextReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type ClearAIContextRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAIContextRes) Reset() {
	*x = ClearAIContextRes{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAIContextRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAIContextRes) ProtoMessage() {}

func (x *ClearAIContextRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAIContextRes.ProtoReflect.Descriptor instead.
func (*ClearAIContextRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"\x87\x01\n" +
	"\x0fGenerateTextReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\x03R\x04uuid\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12#\n" +
	"\rrequest_trace\x18\x04 \x01(\tR\frequestTrace\"%\n" +
	"\x0fGenerateTextRes\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"_\n" +
	"\x10GenerateAudioReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\x03R\x04uuid\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12#\n" +
	"\rrequest_trace\x18\x03 \x01(\tR\frequestTrace\"1\n" +
	"\x10GenerateAudioRes\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\"k\n" +
	"\x11RecognizeAudioReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\x03R\x04uuid\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\x12#\n" +
	"\rrequest_trace\x18\x03 \x01(\tR\frequestTrace\"'\n" +
	"\x11RecognizeAudioRes\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"L\n" +
	"\x11ClearAIContextReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\x03R\x04uuid\x12#\n" +
	"\rrequest_trace\x18\x02 \x01(\tR\frequestTrace\"\x13\n" +
	"\x11ClearAIContextRes2\x86\x02\n" +
	"\tAIService\x12:\n" +
	"\fGenerateText\x12\x13.ai.GenerateTextReq\x1a\x13.ai.GenerateTextRes0\x01\x12;\n" +
	"\rGenerateAudio\x12\x14.ai.GenerateAudioReq\x1a\x14.ai.GenerateAudioRes\x12@\n" +
	"\x0eRecognizeAudio\x12\x15.ai.RecognizeAudioReq\x1a\x15.ai.RecognizeAudioRes0\x01\x12>\n" +
	"\x0eClearAIContext\x12\x15.ai.ClearAIContextReq\x1a\x15.ai.ClearAIContextResB\x19Z\x17generated-ai/;aiserviceb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ai_proto_goTypes = []any{
	(*GenerateTextReq)(nil),   // 0: ai.GenerateTextReq
	(*GenerateTextRes)(nil),   // 1: ai.GenerateTextRes
	(*GenerateAudioReq)(nil),  // 2: ai.GenerateAudioReq
	(*GenerateAudioRes)(nil),  // 3: ai.GenerateAudioRes
	(*RecognizeAudioReq)(nil), // 4: ai.RecognizeAudioReq
	(*RecognizeAudioRes)(nil), // 5: ai.RecognizeAudioRes
	(*ClearAIContextReq)(nil), // 6: ai.ClearAIContextReq
	(*ClearAIContextRes)(nil), // 7: ai.ClearAIContextRes
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: ai.AIService.GenerateText:input_type -> ai.GenerateTextReq
	2, // 1: ai.AIService.GenerateAudio:input_type -> ai.GenerateAudioReq
	4, // 2: ai.AIService.RecognizeAudio:input_type -> ai.RecognizeAudioReq
	6, // 3: ai.AIService.ClearAIContext:input_type -> ai.ClearAIContextReq
	1, // 4: ai.AIService.GenerateText:output_type -> ai.GenerateTextRes
	3, // 5: ai.AIService.GenerateAudio:output_type -> ai.GenerateAudioRes
	5, // 6: ai.AIService.RecognizeAudio:output_type -> ai.RecognizeAudioRes
	7, // 7: ai.AIService.ClearAIContext:output_type -> ai.ClearAIContextRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
