// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: ai.proto

package aiservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_GenerateText_FullMethodName   = "/ai.AIService/GenerateText"
	AIService_GenerateAudio_FullMethodName  = "/ai.AIService/GenerateAudio"
	AIService_RecognizeAudio_FullMethodName = "/ai.AIService/RecognizeAudio"
	AIService_ClearAIContext_FullMethodName = "/ai.AIService/ClearAIContext"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	GenerateText(ctx context.Context, in *GenerateTextReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateTextRes], error)
	GenerateAudio(ctx context.Context, in *GenerateAudioReq, opts ...grpc.CallOption) (*GenerateAudioRes, error)
	RecognizeAudio(ctx context.Context, in *RecognizeAudioReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecognizeAudioRes], error)
	ClearAIContext(ctx context.Context, in *ClearAIContextReq, opts ...grpc.CallOption) (*ClearAIContextRes, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) GenerateText(ctx context.Context, in *GenerateTextReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateTextRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[0], AIService_GenerateText_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateTextReq, GenerateTextRes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_GenerateTextClient = grpc.ServerStreamingClient[GenerateTextRes]

func (c *aIServiceClient) GenerateAudio(ctx context.Context, in *GenerateAudioReq, opts ...grpc.CallOption) (*GenerateAudioRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAudioRes)
	err := c.cc.Invoke(ctx, AIService_GenerateAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) RecognizeAudio(ctx context.Context, in *RecognizeAudioReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecognizeAudioRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[1], AIService_RecognizeAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RecognizeAudioReq, RecognizeAudioRes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_RecognizeAudioClient = grpc.ServerStreamingClient[RecognizeAudioRes]

func (c *aIServiceClient) ClearAIContext(ctx context.Context, in *ClearAIContextReq, opts ...grpc.CallOption) (*ClearAIContextRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearAIContextRes)
	err := c.cc.Invoke(ctx, AIService_ClearAIContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	GenerateText(*GenerateTextReq, grpc.ServerStreamingServer[GenerateTextRes]) error
	GenerateAudio(context.Context, *GenerateAudioReq) (*GenerateAudioRes, error)
	RecognizeAudio(*RecognizeAudioReq, grpc.ServerStreamingServer[RecognizeAudioRes]) error
	ClearAIContext(context.Context, *ClearAIContextReq) (*ClearAIContextRes, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) GenerateText(*GenerateTextReq, grpc.ServerStreamingServer[GenerateTextRes]) error {
	return status.Error(codes.Unimplemented, "method GenerateText not implemented")
}
func (UnimplementedAIServiceServer) GenerateAudio(context.Context, *GenerateAudioReq) (*GenerateAudioRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateAudio not implemented")
}
func (UnimplementedAIServiceServer) RecognizeAudio(*RecognizeAudioReq, grpc.ServerStreamingServer[RecognizeAudioRes]) error {
	return status.Error(codes.Unimplemented, "method RecognizeAudio not implemented")
}
func (UnimplementedAIServiceServer) ClearAIContext(context.Context, *ClearAIContextReq) (*ClearAIContextRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearAIContext not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_GenerateText_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateTextReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).GenerateText(m, &grpc.GenericServerStream[GenerateTextReq, GenerateTextRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_GenerateTextServer = grpc.ServerStreamingServer[GenerateTextRes]

func _AIService_GenerateAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAudioReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateAudio(ctx, req.(*GenerateAudioReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_RecognizeAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RecognizeAudioReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).RecognizeAudio(m, &grpc.GenericServerStream[RecognizeAudioReq, RecognizeAudioRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_RecognizeAudioServer = grpc.ServerStreamingServer[RecognizeAudioRes]

func _AIService_ClearAIContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearAIContextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ClearAIContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ClearAIContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ClearAIContext(ctx, req.(*ClearAIContextReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAudio",
			Handler:    _AIService_GenerateAudio_Handler,
		},
		{
			MethodName: "ClearAIContext",
			Handler:    _AIService_ClearAIContext_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateText",
			Handler:       _AIService_GenerateText_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecognizeAudio",
			Handler:       _AIService_RecognizeAudio_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai.proto",
}
