// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: users.proto

package usersservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestTrace  string                 `protobuf:"bytes,1,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type GetRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // json
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRes) Reset() {
	*x = GetRes{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRes) ProtoMessage() {}

func (x *GetRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRes.ProtoReflect.Descriptor instead.
func (*GetRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

func (x *GetRes) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type UpdSystemPromptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemPrompt  string                 `protobuf:"bytes,1,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,2,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdSystemPromptReq) Reset() {
	*x = UpdSystemPromptReq{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdSystemPromptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdSystemPromptReq) ProtoMessage() {}

func (x *UpdSystemPromptReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdSystemPromptReq.ProtoReflect.Descriptor instead.
func (*UpdSystemPromptReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *UpdSystemPromptReq) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *UpdSystemPromptReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type UpdSystemPromptRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdSystemPromptRes) Reset() {
	*x = UpdSystemPromptRes{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdSystemPromptRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdSystemPromptRes) ProtoMessage() {}

func (x *UpdSystemPromptRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdSystemPromptRes.ProtoReflect.Descriptor instead.
func (*UpdSystemPromptRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

type UpdLangLevelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,2,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdLangLevelReq) Reset() {
	*x = UpdLangLevelReq{}
	mi := &file_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdLangLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdLangLevelReq) ProtoMessage() {}

func (x *UpdLangLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdLangLevelReq.ProtoReflect.Descriptor instead.
func (*UpdLangLevelReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{4}
}

func (x *UpdLangLevelReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UpdLangLevelReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type UpdLangLevelRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdLangLevelRes) Reset() {
	*x = UpdLangLevelRes{}
	mi := &file_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdLangLevelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdLangLevelRes) ProtoMessage() {}

func (x *UpdLangLevelRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdLangLevelRes.ProtoReflect.Descriptor instead.
func (*UpdLangLevelRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{5}
}

type UpdStreakReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correct       bool                   `protobuf:"varint,1,opt,name=correct,proto3" json:"correct,omitempty"`
	Theme         string                 `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	Counter       int32                  `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,4,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdStreakReq) Reset() {
	*x = UpdStreakReq{}
	mi := &file_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdStreakReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdStreakReq) ProtoMessage() {}

func (x *UpdStreakReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdStreakReq.ProtoReflect.Descriptor instead.
func (*UpdStreakReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{6}
}

func (x *UpdStreakReq) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *UpdStreakReq) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UpdStreakReq) GetCounter() int32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *UpdStreakReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type UpdStreakRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdStreakRes) Reset() {
	*x = UpdStreakRes{}
	mi := &file_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdStreakRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdStreakRes) ProtoMessage() {}

func (x *UpdStreakRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdStreakRes.ProtoReflect.Descriptor instead.
func (*UpdStreakRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{7}
}

type UpdTaskIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Add           int32                  `protobuf:"varint,1,opt,name=add,proto3" json:"add,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,2,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdTaskIDReq) Reset() {
	*x = UpdTaskIDReq{}
	mi := &file_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdTaskIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdTaskIDReq) ProtoMessage() {}

func (x *UpdTaskIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdTaskIDReq.ProtoReflect.Descriptor instead.
func (*UpdTaskIDReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{8}
}

func (x *UpdTaskIDReq) GetAdd() int32 {
	if x != nil {
		return x.Add
	}
	return 0
}

func (x *UpdTaskIDReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type UpdTaskIDRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdTaskIDRes) Reset() {
	*x = UpdTaskIDRes{}
	mi := &file_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdTaskIDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdTaskIDRes) ProtoMessage() {}

func (x *UpdTaskIDRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdTaskIDRes.ProtoReflect.Descriptor instead.
func (*UpdTaskIDRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{9}
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x05users\"-\n" +
	"\x06GetReq\x12#\n" +
	"\rrequest_trace\x18\x01 \x01(\tR\frequestTrace\"\x1c\n" +
	"\x06GetRes\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"^\n" +
	"\x12UpdSystemPromptReq\x12#\n" +
	"\rsystem_prompt\x18\x01 \x01(\tR\fsystemPrompt\x12#\n" +
	"\rrequest_trace\x18\x02 \x01(\tR\frequestTrace\"\x14\n" +
	"\x12UpdSystemPromptRes\"L\n" +
	"\x0fUpdLangLevelReq\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12#\n" +
	"\rrequest_trace\x18\x02 \x01(\tR\frequestTrace\"\x11\n" +
	"\x0fUpdLangLevelRes\"}\n" +
	"\fUpdStreakReq\x12\x18\n" +
	"\acorrect\x18\x01 \x01(\bR\acorrect\x12\x14\n" +
	"\x05theme\x18\x02 \x01(\tR\x05theme\x12\x18\n" +
	"\acounter\x18\x03 \x01(\x05R\acounter\x12#\n" +
	"\rrequest_trace\x18\x04 \x01(\tR\frequestTrace\"\x0e\n" +
	"\fUpdStreakRes\"E\n" +
	"\fUpdTaskIDReq\x12\x10\n" +
	"\x03add\x18\x01 \x01(\x05R\x03add\x12#\n" +
	"\rrequest_trace\x18\x02 \x01(\tR\frequestTrace\"\x0e\n" +
	"\fUpdTaskIDRes2\xae\x02\n" +
	"\fUsersService\x12'\n" +
	"\aGetUser\x12\r.users.GetReq\x1a\r.users.GetRes\x12G\n" +
	"\x0fUpdSystemPrompt\x12\x19.users.UpdSystemPromptReq\x1a\x19.users.UpdSystemPromptRes\x12>\n" +
	"\fUpdLangLevel\x12\x16.users.UpdLangLevelReq\x1a\x16.users.UpdLangLevelRes\x125\n" +
	"\tUpdStreak\x12\x13.users.UpdStreakReq\x1a\x13.users.UpdStreakRes\x125\n" +
	"\tUpdTaskID\x12\x13.users.UpdTaskIDReq\x1a\x13.users.UpdTaskIDResB\x1fZ\x1dgenerated-users/;usersserviceb\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_users_proto_goTypes = []any{
	(*GetReq)(nil),             // 0: users.GetReq
	(*GetRes)(nil),             // 1: users.GetRes
	(*UpdSystemPromptReq)(nil), // 2: users.UpdSystemPromptReq
	(*UpdSystemPromptRes)(nil), // 3: users.UpdSystemPromptRes
	(*UpdLangLevelReq)(nil),    // 4: users.UpdLangLevelReq
	(*UpdLangLevelRes)(nil),    // 5: users.UpdLangLevelRes
	(*UpdStreakReq)(nil),       // 6: users.UpdStreakReq
	(*UpdStreakRes)(nil),       // 7: users.UpdStreakRes
	(*UpdTaskIDReq)(nil),       // 8: users.UpdTaskIDReq
	(*UpdTaskIDRes)(nil),       // 9: users.UpdTaskIDRes
}
var file_users_proto_depIdxs = []int32{
	0, // 0: users.UsersService.GetUser:input_type -> users.GetReq
	2, // 1: users.UsersService.UpdSystemPrompt:input_type -> users.UpdSystemPromptReq
	4, // 2: users.UsersService.UpdLangLevel:input_type -> users.UpdLangLevelReq
	6, // 3: users.UsersService.UpdStreak:input_type -> users.UpdStreakReq
	8, // 4: users.UsersService.UpdTaskID:input_type -> users.UpdTaskIDReq
	1, // 5: users.UsersService.GetUser:output_type -> users.GetRes
	3, // 6: users.UsersService.UpdSystemPrompt:output_type -> users.UpdSystemPromptRes
	5, // 7: users.UsersService.UpdLangLevel:output_type -> users.UpdLangLevelRes
	7, // 8: users.UsersService.UpdStreak:output_type -> users.UpdStreakRes
	9, // 9: users.UsersService.UpdTaskID:output_type -> users.UpdTaskIDRes
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
