// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: users.proto

package usersservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsersService_RegUser_FullMethodName         = "/users.UsersService/RegUser"
	UsersService_GetUser_FullMethodName         = "/users.UsersService/GetUser"
	UsersService_UpdSystemPrompt_FullMethodName = "/users.UsersService/UpdSystemPrompt"
	UsersService_UpdLangLevel_FullMethodName    = "/users.UsersService/UpdLangLevel"
	UsersService_DelUser_FullMethodName         = "/users.UsersService/DelUser"
)

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersServiceClient interface {
	RegUser(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRes, error)
	GetUser(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error)
	UpdSystemPrompt(ctx context.Context, in *UpdSystemPromptReq, opts ...grpc.CallOption) (*UpdSystemPromptRes, error)
	UpdLangLevel(ctx context.Context, in *UpdLangLevelReq, opts ...grpc.CallOption) (*UpdLangLevelRes, error)
	DelUser(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*DelRes, error)
}

type usersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersServiceClient(cc grpc.ClientConnInterface) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) RegUser(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegRes)
	err := c.cc.Invoke(ctx, UsersService_RegUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUser(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRes)
	err := c.cc.Invoke(ctx, UsersService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdSystemPrompt(ctx context.Context, in *UpdSystemPromptReq, opts ...grpc.CallOption) (*UpdSystemPromptRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdSystemPromptRes)
	err := c.cc.Invoke(ctx, UsersService_UpdSystemPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdLangLevel(ctx context.Context, in *UpdLangLevelReq, opts ...grpc.CallOption) (*UpdLangLevelRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdLangLevelRes)
	err := c.cc.Invoke(ctx, UsersService_UpdLangLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DelUser(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*DelRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelRes)
	err := c.cc.Invoke(ctx, UsersService_DelUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
// All implementations must embed UnimplementedUsersServiceServer
// for forward compatibility.
type UsersServiceServer interface {
	RegUser(context.Context, *RegReq) (*RegRes, error)
	GetUser(context.Context, *GetReq) (*GetRes, error)
	UpdSystemPrompt(context.Context, *UpdSystemPromptReq) (*UpdSystemPromptRes, error)
	UpdLangLevel(context.Context, *UpdLangLevelReq) (*UpdLangLevelRes, error)
	DelUser(context.Context, *DelReq) (*DelRes, error)
	mustEmbedUnimplementedUsersServiceServer()
}

// UnimplementedUsersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsersServiceServer struct{}

func (UnimplementedUsersServiceServer) RegUser(context.Context, *RegReq) (*RegRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RegUser not implemented")
}
func (UnimplementedUsersServiceServer) GetUser(context.Context, *GetReq) (*GetRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUsersServiceServer) UpdSystemPrompt(context.Context, *UpdSystemPromptReq) (*UpdSystemPromptRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdSystemPrompt not implemented")
}
func (UnimplementedUsersServiceServer) UpdLangLevel(context.Context, *UpdLangLevelReq) (*UpdLangLevelRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdLangLevel not implemented")
}
func (UnimplementedUsersServiceServer) DelUser(context.Context, *DelReq) (*DelRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUser not implemented")
}
func (UnimplementedUsersServiceServer) mustEmbedUnimplementedUsersServiceServer() {}
func (UnimplementedUsersServiceServer) testEmbeddedByValue()                      {}

// UnsafeUsersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServiceServer will
// result in compilation errors.
type UnsafeUsersServiceServer interface {
	mustEmbedUnimplementedUsersServiceServer()
}

func RegisterUsersServiceServer(s grpc.ServiceRegistrar, srv UsersServiceServer) {
	// If the following call panics, it indicates UnimplementedUsersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsersService_ServiceDesc, srv)
}

func _UsersService_RegUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).RegUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_RegUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).RegUser(ctx, req.(*RegReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUser(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdSystemPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdSystemPromptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdSystemPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_UpdSystemPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdSystemPrompt(ctx, req.(*UpdSystemPromptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdLangLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdLangLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdLangLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_UpdLangLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdLangLevel(ctx, req.(*UpdLangLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DelUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DelUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersService_DelUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DelUser(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersService_ServiceDesc is the grpc.ServiceDesc for UsersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegUser",
			Handler:    _UsersService_RegUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UsersService_GetUser_Handler,
		},
		{
			MethodName: "UpdSystemPrompt",
			Handler:    _UsersService_UpdSystemPrompt_Handler,
		},
		{
			MethodName: "UpdLangLevel",
			Handler:    _UsersService_UpdLangLevel_Handler,
		},
		{
			MethodName: "DelUser",
			Handler:    _UsersService_DelUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
