// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: learn.proto

package learnservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LearnService_NewTasks_FullMethodName           = "/learn.LearnService/NewTasks"
	LearnService_GetTasks_FullMethodName           = "/learn.LearnService/GetTasks"
	LearnService_DelTask_FullMethodName            = "/learn.LearnService/DelTask"
	LearnService_NewWords_FullMethodName           = "/learn.LearnService/NewWords"
	LearnService_GetWords_FullMethodName           = "/learn.LearnService/GetWords"
	LearnService_GetWordsWithTarget_FullMethodName = "/learn.LearnService/GetWordsWithTarget"
	LearnService_DelWord_FullMethodName            = "/learn.LearnService/DelWord"
)

// LearnServiceClient is the client API for LearnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LearnServiceClient interface {
	NewTasks(ctx context.Context, in *NewTasksReq, opts ...grpc.CallOption) (*NewTasksRes, error)
	GetTasks(ctx context.Context, in *GetTasksReq, opts ...grpc.CallOption) (*GetTasksRes, error)
	DelTask(ctx context.Context, in *DelTaskReq, opts ...grpc.CallOption) (*DelTaskRes, error)
	NewWords(ctx context.Context, in *NewWordsReq, opts ...grpc.CallOption) (*NewWordsRes, error)
	GetWords(ctx context.Context, in *GetWordsReq, opts ...grpc.CallOption) (*GetWordsRes, error)
	GetWordsWithTarget(ctx context.Context, in *GetWordsWithTargetReq, opts ...grpc.CallOption) (*GetWordsWithTargetRes, error)
	DelWord(ctx context.Context, in *DelWordReq, opts ...grpc.CallOption) (*DelWordRes, error)
}

type learnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLearnServiceClient(cc grpc.ClientConnInterface) LearnServiceClient {
	return &learnServiceClient{cc}
}

func (c *learnServiceClient) NewTasks(ctx context.Context, in *NewTasksReq, opts ...grpc.CallOption) (*NewTasksRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewTasksRes)
	err := c.cc.Invoke(ctx, LearnService_NewTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learnServiceClient) GetTasks(ctx context.Context, in *GetTasksReq, opts ...grpc.CallOption) (*GetTasksRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTasksRes)
	err := c.cc.Invoke(ctx, LearnService_GetTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learnServiceClient) DelTask(ctx context.Context, in *DelTaskReq, opts ...grpc.CallOption) (*DelTaskRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelTaskRes)
	err := c.cc.Invoke(ctx, LearnService_DelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learnServiceClient) NewWords(ctx context.Context, in *NewWordsReq, opts ...grpc.CallOption) (*NewWordsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewWordsRes)
	err := c.cc.Invoke(ctx, LearnService_NewWords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learnServiceClient) GetWords(ctx context.Context, in *GetWordsReq, opts ...grpc.CallOption) (*GetWordsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWordsRes)
	err := c.cc.Invoke(ctx, LearnService_GetWords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learnServiceClient) GetWordsWithTarget(ctx context.Context, in *GetWordsWithTargetReq, opts ...grpc.CallOption) (*GetWordsWithTargetRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWordsWithTargetRes)
	err := c.cc.Invoke(ctx, LearnService_GetWordsWithTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learnServiceClient) DelWord(ctx context.Context, in *DelWordReq, opts ...grpc.CallOption) (*DelWordRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelWordRes)
	err := c.cc.Invoke(ctx, LearnService_DelWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LearnServiceServer is the server API for LearnService service.
// All implementations must embed UnimplementedLearnServiceServer
// for forward compatibility.
type LearnServiceServer interface {
	NewTasks(context.Context, *NewTasksReq) (*NewTasksRes, error)
	GetTasks(context.Context, *GetTasksReq) (*GetTasksRes, error)
	DelTask(context.Context, *DelTaskReq) (*DelTaskRes, error)
	NewWords(context.Context, *NewWordsReq) (*NewWordsRes, error)
	GetWords(context.Context, *GetWordsReq) (*GetWordsRes, error)
	GetWordsWithTarget(context.Context, *GetWordsWithTargetReq) (*GetWordsWithTargetRes, error)
	DelWord(context.Context, *DelWordReq) (*DelWordRes, error)
	mustEmbedUnimplementedLearnServiceServer()
}

// UnimplementedLearnServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLearnServiceServer struct{}

func (UnimplementedLearnServiceServer) NewTasks(context.Context, *NewTasksReq) (*NewTasksRes, error) {
	return nil, status.Error(codes.Unimplemented, "method NewTasks not implemented")
}
func (UnimplementedLearnServiceServer) GetTasks(context.Context, *GetTasksReq) (*GetTasksRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTasks not implemented")
}
func (UnimplementedLearnServiceServer) DelTask(context.Context, *DelTaskReq) (*DelTaskRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DelTask not implemented")
}
func (UnimplementedLearnServiceServer) NewWords(context.Context, *NewWordsReq) (*NewWordsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method NewWords not implemented")
}
func (UnimplementedLearnServiceServer) GetWords(context.Context, *GetWordsReq) (*GetWordsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWords not implemented")
}
func (UnimplementedLearnServiceServer) GetWordsWithTarget(context.Context, *GetWordsWithTargetReq) (*GetWordsWithTargetRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWordsWithTarget not implemented")
}
func (UnimplementedLearnServiceServer) DelWord(context.Context, *DelWordReq) (*DelWordRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DelWord not implemented")
}
func (UnimplementedLearnServiceServer) mustEmbedUnimplementedLearnServiceServer() {}
func (UnimplementedLearnServiceServer) testEmbeddedByValue()                      {}

// UnsafeLearnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LearnServiceServer will
// result in compilation errors.
type UnsafeLearnServiceServer interface {
	mustEmbedUnimplementedLearnServiceServer()
}

func RegisterLearnServiceServer(s grpc.ServiceRegistrar, srv LearnServiceServer) {
	// If the following call panics, it indicates UnimplementedLearnServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LearnService_ServiceDesc, srv)
}

func _LearnService_NewTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnServiceServer).NewTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnService_NewTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnServiceServer).NewTasks(ctx, req.(*NewTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearnService_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnServiceServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnService_GetTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnServiceServer).GetTasks(ctx, req.(*GetTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearnService_DelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnServiceServer).DelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnService_DelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnServiceServer).DelTask(ctx, req.(*DelTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearnService_NewWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewWordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnServiceServer).NewWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnService_NewWords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnServiceServer).NewWords(ctx, req.(*NewWordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearnService_GetWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnServiceServer).GetWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnService_GetWords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnServiceServer).GetWords(ctx, req.(*GetWordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearnService_GetWordsWithTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWordsWithTargetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnServiceServer).GetWordsWithTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnService_GetWordsWithTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnServiceServer).GetWordsWithTarget(ctx, req.(*GetWordsWithTargetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearnService_DelWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelWordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnServiceServer).DelWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnService_DelWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnServiceServer).DelWord(ctx, req.(*DelWordReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LearnService_ServiceDesc is the grpc.ServiceDesc for LearnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LearnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "learn.LearnService",
	HandlerType: (*LearnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTasks",
			Handler:    _LearnService_NewTasks_Handler,
		},
		{
			MethodName: "GetTasks",
			Handler:    _LearnService_GetTasks_Handler,
		},
		{
			MethodName: "DelTask",
			Handler:    _LearnService_DelTask_Handler,
		},
		{
			MethodName: "NewWords",
			Handler:    _LearnService_NewWords_Handler,
		},
		{
			MethodName: "GetWords",
			Handler:    _LearnService_GetWords_Handler,
		},
		{
			MethodName: "GetWordsWithTarget",
			Handler:    _LearnService_GetWordsWithTarget_Handler,
		},
		{
			MethodName: "DelWord",
			Handler:    _LearnService_DelWord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "learn.proto",
}
