// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: learn.proto

package learnservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"` // full pages
	RequestTrace  string                 `protobuf:"bytes,2,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTasksReq) Reset() {
	*x = NewTasksReq{}
	mi := &file_learn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTasksReq) ProtoMessage() {}

func (x *NewTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTasksReq.ProtoReflect.Descriptor instead.
func (*NewTasksReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{0}
}

func (x *NewTasksReq) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

func (x *NewTasksReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type NewTasksRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int32                  `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTasksRes) Reset() {
	*x = NewTasksRes{}
	mi := &file_learn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTasksRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTasksRes) ProtoMessage() {}

func (x *NewTasksRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTasksRes.ProtoReflect.Descriptor instead.
func (*NewTasksRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{1}
}

func (x *NewTasksRes) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

type GetTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,4,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksReq) Reset() {
	*x = GetTasksReq{}
	mi := &file_learn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksReq) ProtoMessage() {}

func (x *GetTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksReq.ProtoReflect.Descriptor instead.
func (*GetTasksReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{2}
}

func (x *GetTasksReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *GetTasksReq) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *GetTasksReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTasksReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type GetTasksRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksRes) Reset() {
	*x = GetTasksRes{}
	mi := &file_learn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRes) ProtoMessage() {}

func (x *GetTasksRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRes.ProtoReflect.Descriptor instead.
func (*GetTasksRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{3}
}

func (x *GetTasksRes) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type DelTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,3,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelTaskReq) Reset() {
	*x = DelTaskReq{}
	mi := &file_learn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTaskReq) ProtoMessage() {}

func (x *DelTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTaskReq.ProtoReflect.Descriptor instead.
func (*DelTaskReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{4}
}

func (x *DelTaskReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *DelTaskReq) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *DelTaskReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type DelTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelTaskRes) Reset() {
	*x = DelTaskRes{}
	mi := &file_learn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTaskRes) ProtoMessage() {}

func (x *DelTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTaskRes.ProtoReflect.Descriptor instead.
func (*DelTaskRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{5}
}

type NewWordsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"` // many words with explanations in json format
	RequestTrace  string                 `protobuf:"bytes,2,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewWordsReq) Reset() {
	*x = NewWordsReq{}
	mi := &file_learn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewWordsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewWordsReq) ProtoMessage() {}

func (x *NewWordsReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewWordsReq.ProtoReflect.Descriptor instead.
func (*NewWordsReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{6}
}

func (x *NewWordsReq) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

func (x *NewWordsReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type NewWordsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int32                  `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewWordsRes) Reset() {
	*x = NewWordsRes{}
	mi := &file_learn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewWordsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewWordsRes) ProtoMessage() {}

func (x *NewWordsRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewWordsRes.ProtoReflect.Descriptor instead.
func (*NewWordsRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{7}
}

func (x *NewWordsRes) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

type GetWordsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchData    string                 `protobuf:"bytes,1,opt,name=search_data,json=searchData,proto3" json:"search_data,omitempty"` // word or serial number
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,3,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordsReq) Reset() {
	*x = GetWordsReq{}
	mi := &file_learn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordsReq) ProtoMessage() {}

func (x *GetWordsReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordsReq.ProtoReflect.Descriptor instead.
func (*GetWordsReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{8}
}

func (x *GetWordsReq) GetSearchData() string {
	if x != nil {
		return x.SearchData
	}
	return ""
}

func (x *GetWordsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWordsReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type GetWordsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordsRes) Reset() {
	*x = GetWordsRes{}
	mi := &file_learn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordsRes) ProtoMessage() {}

func (x *GetWordsRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordsRes.ProtoReflect.Descriptor instead.
func (*GetWordsRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{9}
}

func (x *GetWordsRes) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetWordsWithTargetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserWord      string                 `protobuf:"bytes,1,opt,name=user_word,json=userWord,proto3" json:"user_word,omitempty"`
	FirstLetter   string                 `protobuf:"bytes,2,opt,name=first_letter,json=firstLetter,proto3" json:"first_letter,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	OffsetId      int32                  `protobuf:"varint,4,opt,name=offset_id,json=offsetId,proto3" json:"offset_id,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,5,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordsWithTargetReq) Reset() {
	*x = GetWordsWithTargetReq{}
	mi := &file_learn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordsWithTargetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordsWithTargetReq) ProtoMessage() {}

func (x *GetWordsWithTargetReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordsWithTargetReq.ProtoReflect.Descriptor instead.
func (*GetWordsWithTargetReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{10}
}

func (x *GetWordsWithTargetReq) GetUserWord() string {
	if x != nil {
		return x.UserWord
	}
	return ""
}

func (x *GetWordsWithTargetReq) GetFirstLetter() string {
	if x != nil {
		return x.FirstLetter
	}
	return ""
}

func (x *GetWordsWithTargetReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWordsWithTargetReq) GetOffsetId() int32 {
	if x != nil {
		return x.OffsetId
	}
	return 0
}

func (x *GetWordsWithTargetReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type GetWordsWithTargetRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`    // json as 'GetWordsRes'
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"` // user_word in data?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordsWithTargetRes) Reset() {
	*x = GetWordsWithTargetRes{}
	mi := &file_learn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordsWithTargetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordsWithTargetRes) ProtoMessage() {}

func (x *GetWordsWithTargetRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordsWithTargetRes.ProtoReflect.Descriptor instead.
func (*GetWordsWithTargetRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{11}
}

func (x *GetWordsWithTargetRes) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GetWordsWithTargetRes) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DelWordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`      // 1 word
	Serial        int32                  `protobuf:"varint,2,opt,name=serial,proto3" json:"serial,omitempty"` // 1 serial number
	RequestTrace  string                 `protobuf:"bytes,3,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelWordReq) Reset() {
	*x = DelWordReq{}
	mi := &file_learn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelWordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelWordReq) ProtoMessage() {}

func (x *DelWordReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelWordReq.ProtoReflect.Descriptor instead.
func (*DelWordReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{12}
}

func (x *DelWordReq) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *DelWordReq) GetSerial() int32 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *DelWordReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type DelWordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelWordRes) Reset() {
	*x = DelWordRes{}
	mi := &file_learn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelWordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelWordRes) ProtoMessage() {}

func (x *DelWordRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelWordRes.ProtoReflect.Descriptor instead.
func (*DelWordRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{13}
}

var File_learn_proto protoreflect.FileDescriptor

const file_learn_proto_rawDesc = "" +
	"\n" +
	"\vlearn.proto\x12\x05learn\"O\n" +
	"\vNewTasksReq\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonData\x12#\n" +
	"\rrequest_trace\x18\x02 \x01(\tR\frequestTrace\")\n" +
	"\vNewTasksRes\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x05R\binserted\"z\n" +
	"\vGetTasksReq\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12#\n" +
	"\rrequest_trace\x18\x04 \x01(\tR\frequestTrace\"!\n" +
	"\vGetTasksRes\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"c\n" +
	"\n" +
	"DelTaskReq\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12#\n" +
	"\rrequest_trace\x18\x03 \x01(\tR\frequestTrace\"\f\n" +
	"\n" +
	"DelTaskRes\"O\n" +
	"\vNewWordsReq\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonData\x12#\n" +
	"\rrequest_trace\x18\x02 \x01(\tR\frequestTrace\")\n" +
	"\vNewWordsRes\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x05R\binserted\"i\n" +
	"\vGetWordsReq\x12\x1f\n" +
	"\vsearch_data\x18\x01 \x01(\tR\n" +
	"searchData\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12#\n" +
	"\rrequest_trace\x18\x03 \x01(\tR\frequestTrace\"!\n" +
	"\vGetWordsRes\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\xaf\x01\n" +
	"\x15GetWordsWithTargetReq\x12\x1b\n" +
	"\tuser_word\x18\x01 \x01(\tR\buserWord\x12!\n" +
	"\ffirst_letter\x18\x02 \x01(\tR\vfirstLetter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\toffset_id\x18\x04 \x01(\x05R\boffsetId\x12#\n" +
	"\rrequest_trace\x18\x05 \x01(\tR\frequestTrace\"A\n" +
	"\x15GetWordsWithTargetRes\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"]\n" +
	"\n" +
	"DelWordReq\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\x05R\x06serial\x12#\n" +
	"\rrequest_trace\x18\x03 \x01(\tR\frequestTrace\"\f\n" +
	"\n" +
	"DelWordRes2\x92\x03\n" +
	"\fLearnService\x122\n" +
	"\bNewTasks\x12\x12.learn.NewTasksReq\x1a\x12.learn.NewTasksRes\x122\n" +
	"\bGetTasks\x12\x12.learn.GetTasksReq\x1a\x12.learn.GetTasksRes\x12/\n" +
	"\aDelTask\x12\x11.learn.DelTaskReq\x1a\x11.learn.DelTaskRes\x122\n" +
	"\bNewWords\x12\x12.learn.NewWordsReq\x1a\x12.learn.NewWordsRes\x122\n" +
	"\bGetWords\x12\x12.learn.GetWordsReq\x1a\x12.learn.GetWordsRes\x12P\n" +
	"\x12GetWordsWithTarget\x12\x1c.learn.GetWordsWithTargetReq\x1a\x1c.learn.GetWordsWithTargetRes\x12/\n" +
	"\aDelWord\x12\x11.learn.DelWordReq\x1a\x11.learn.DelWordResB\x1fZ\x1dgenerated-learn/;learnserviceb\x06proto3"

var (
	file_learn_proto_rawDescOnce sync.Once
	file_learn_proto_rawDescData []byte
)

func file_learn_proto_rawDescGZIP() []byte {
	file_learn_proto_rawDescOnce.Do(func() {
		file_learn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learn_proto_rawDesc), len(file_learn_proto_rawDesc)))
	})
	return file_learn_proto_rawDescData
}

var file_learn_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_learn_proto_goTypes = []any{
	(*NewTasksReq)(nil),           // 0: learn.NewTasksReq
	(*NewTasksRes)(nil),           // 1: learn.NewTasksRes
	(*GetTasksReq)(nil),           // 2: learn.GetTasksReq
	(*GetTasksRes)(nil),           // 3: learn.GetTasksRes
	(*DelTaskReq)(nil),            // 4: learn.DelTaskReq
	(*DelTaskRes)(nil),            // 5: learn.DelTaskRes
	(*NewWordsReq)(nil),           // 6: learn.NewWordsReq
	(*NewWordsRes)(nil),           // 7: learn.NewWordsRes
	(*GetWordsReq)(nil),           // 8: learn.GetWordsReq
	(*GetWordsRes)(nil),           // 9: learn.GetWordsRes
	(*GetWordsWithTargetReq)(nil), // 10: learn.GetWordsWithTargetReq
	(*GetWordsWithTargetRes)(nil), // 11: learn.GetWordsWithTargetRes
	(*DelWordReq)(nil),            // 12: learn.DelWordReq
	(*DelWordRes)(nil),            // 13: learn.DelWordRes
}
var file_learn_proto_depIdxs = []int32{
	0,  // 0: learn.LearnService.NewTasks:input_type -> learn.NewTasksReq
	2,  // 1: learn.LearnService.GetTasks:input_type -> learn.GetTasksReq
	4,  // 2: learn.LearnService.DelTask:input_type -> learn.DelTaskReq
	6,  // 3: learn.LearnService.NewWords:input_type -> learn.NewWordsReq
	8,  // 4: learn.LearnService.GetWords:input_type -> learn.GetWordsReq
	10, // 5: learn.LearnService.GetWordsWithTarget:input_type -> learn.GetWordsWithTargetReq
	12, // 6: learn.LearnService.DelWord:input_type -> learn.DelWordReq
	1,  // 7: learn.LearnService.NewTasks:output_type -> learn.NewTasksRes
	3,  // 8: learn.LearnService.GetTasks:output_type -> learn.GetTasksRes
	5,  // 9: learn.LearnService.DelTask:output_type -> learn.DelTaskRes
	7,  // 10: learn.LearnService.NewWords:output_type -> learn.NewWordsRes
	9,  // 11: learn.LearnService.GetWords:output_type -> learn.GetWordsRes
	11, // 12: learn.LearnService.GetWordsWithTarget:output_type -> learn.GetWordsWithTargetRes
	13, // 13: learn.LearnService.DelWord:output_type -> learn.DelWordRes
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_learn_proto_init() }
func file_learn_proto_init() {
	if File_learn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learn_proto_rawDesc), len(file_learn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learn_proto_goTypes,
		DependencyIndexes: file_learn_proto_depIdxs,
		MessageInfos:      file_learn_proto_msgTypes,
	}.Build()
	File_learn_proto = out.File
	file_learn_proto_goTypes = nil
	file_learn_proto_depIdxs = nil
}
